trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# Install Terraform (Microsoft DevLabs version)
- task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
  displayName: "Install Terraform"
  inputs:
    terraformVersion: '1.9.5'

# Hello world step
- script: echo "Hello, world!"
  displayName: "Run a one-line script"

- script: |
    echo "Add other tasks to build, test, and deploy your project."
    echo "See https://aka.ms/yaml"
  displayName: "Run a multi-line script"

# Terraform Init
- task: TerraformTaskV3@3
  displayName: "Terraform Init"
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    backendServiceArm: 'terraforminfrabuild'
    backendAzureRmResourceGroupName: 'rg-terraform'
    backendAzureRmStorageAccountName: 'saterraform123'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'terra.tfstate'

# ✅ Install Checkov
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
  displayName: "Use Python 3"

- script: |
    pip install checkov
  displayName: "Install Checkov"

# ✅ Run Checkov security scan on Terraform code
- script: |
    checkov -d $(System.DefaultWorkingDirectory) -o junitxml > checkov-report.xml
  displayName: "Run Checkov Scan"

# ✅ Publish Checkov results in Azure DevOps
- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/checkov-report.xml'
    testRunTitle: "Checkov Terraform Security Scan"

# Terraform Validate
- task: TerraformTaskV3@3
  displayName: "Terraform Validate"
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: '$(System.DefaultWorkingDirectory)'

# Terraform Plan
- task: TerraformTaskV3@3
  displayName: "Terraform Plan"
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    environmentServiceNameAzureRM: 'terraforminfrabuild'

# Terraform Apply
- task: TerraformTaskV3@3
  displayName: "Terraform Apply"
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    environmentServiceNameAzureRM: 'terraforminfrabuild'
    commandOptions: '-auto-approve'
